DROP TABLE IF EXISTS LEASE_TO_META_DATA_MAPPING;
DROP TABLE IF EXISTS LEASE_TO_LEASE_INCIDENTAL_MAPPING;
DROP TABLE IF EXISTS LEASE_TO_TENANT_MAPPING;
DROP TABLE IF EXISTS LEASE_TO_PREMISES_MAPPING;
DROP TABLE IF EXISTS LEASE_TO_CATEGORY_MAPPING;
DROP TABLE IF EXISTS LEASE_TO_BOND_MAPPING;

DROP TABLE IF EXISTS LEASE_META_DATA;
DROP TABLE IF EXISTS LEASE_INCIDENTAL;
DROP TABLE IF EXISTS LEASE_BOND;
DROP TABLE IF EXISTS LEASE;

DROP TABLE IF EXISTS LEASE_PREMISES;
DROP TABLE IF EXISTS LEASE_TENANT;
DROP TABLE IF EXISTS LEASE_CATEGORY;

CREATE TABLE IF NOT EXISTS LEASE_TENANT (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEASE_CATEGORY (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	CATEGORY_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEASE_PREMISES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ADDRESS VARCHAR(200) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEASE_BOND (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	BOND_TYPE VARCHAR(20) NOT NULL,
	BOND_AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	BOND_NOTES VARCHAR(1000) NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEASE_META_DATA (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	META_DATA_TYPE VARCHAR(30) NOT NULL,
	META_DATA_DESCRIPTION VARCHAR(150) NOT NULL,
	META_DATA_VALUE VARCHAR(150) NOT NULL,
	META_DATA_ORDER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEASE (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	LEASE_START DATE NOT NULL,
	LEASE_END DATE NOT NULL,
	LAST_UPDATE DATE NULL,
	NOTES VARCHAR(1000) NULL,
	UNITS VARCHAR(100) NOT NULL,
	AREA DECIMAL(10,2) NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEASE_INCIDENTAL (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	AMOUNT DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	PERCENTAGE DECIMAL(10,4) NOT NULL DEFAULT 0.00,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEASE_TO_META_DATA_MAPPING (
	LEASE_ID INTEGER NOT NULL,
	META_DATA_ID INTEGER NOT NULL,
	FOREIGN KEY (LEASE_ID)  REFERENCES LEASE(ID),
	FOREIGN KEY (META_DATA_ID)  REFERENCES LEASE_META_DATA(ID),
	PRIMARY KEY (LEASE_ID, META_DATA_ID)
);

CREATE TABLE IF NOT EXISTS LEASE_TO_LEASE_INCIDENTAL_MAPPING (
	LEASE_ID INTEGER NOT NULL,
	LEASE_INCIDENTAL_ID INTEGER NOT NULL,
	FOREIGN KEY (LEASE_ID)  REFERENCES LEASE(ID),
	FOREIGN KEY (LEASE_INCIDENTAL_ID)  REFERENCES LEASE_INCIDENTAL(ID),
	PRIMARY KEY (LEASE_ID, LEASE_INCIDENTAL_ID)
);

CREATE TABLE IF NOT EXISTS LEASE_TO_TENANT_MAPPING (
	LEASE_ID INTEGER NOT NULL,
	TENANT_ID INTEGER NOT NULL,
	FOREIGN KEY (LEASE_ID)  REFERENCES LEASE(ID),
	FOREIGN KEY (TENANT_ID)  REFERENCES LEASE_TENANT(ID),
	PRIMARY KEY (LEASE_ID, TENANT_ID)
);


CREATE TABLE IF NOT EXISTS LEASE_TO_PREMISES_MAPPING (
	LEASE_ID INTEGER NOT NULL,
	PREMISES_ID INTEGER NOT NULL,
	FOREIGN KEY (LEASE_ID)  REFERENCES LEASE(ID),
	FOREIGN KEY (PREMISES_ID)  REFERENCES LEASE_PREMISES(ID),
	PRIMARY KEY (LEASE_ID, PREMISES_ID)
);


CREATE TABLE IF NOT EXISTS LEASE_TO_CATEGORY_MAPPING (
	LEASE_ID INTEGER NOT NULL,
	CATEGORY_ID INTEGER NOT NULL,
	FOREIGN KEY (LEASE_ID)  REFERENCES LEASE(ID),
	FOREIGN KEY (CATEGORY_ID)  REFERENCES LEASE_CATEGORY(ID),
	PRIMARY KEY (LEASE_ID, CATEGORY_ID)
);

CREATE TABLE IF NOT EXISTS LEASE_TO_BOND_MAPPING (
	LEASE_ID INTEGER NOT NULL,
	BOND_ID INTEGER NOT NULL,
	FOREIGN KEY (LEASE_ID)  REFERENCES LEASE(ID),
	FOREIGN KEY (BOND_ID)  REFERENCES LEASE_BOND(ID),
	PRIMARY KEY (LEASE_ID, BOND_ID)
);