ALTER TABLE LEASE ADD RESIDENTIAL BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE LEASE ADD INACTIVE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE LEASE ADD HAS_OPTION BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE LEASE ADD OPTION_START_DATE DATE NULL;
ALTER TABLE LEASE ADD OPTION_END_DATE DATE NULL;

ALTER TABLE LEASE_CATEGORY ADD CATEGORY_COMPANY VARCHAR(100) NULL;
ALTER TABLE LEASE_CATEGORY ADD CATEGORY_ABN VARCHAR(20) NULL;
ALTER TABLE LEASE_CATEGORY ADD CATEGORY_ADDRESS VARCHAR(200) NULL;
ALTER TABLE LEASE_CATEGORY ADD CATEGORY_PHONE VARCHAR(100) NULL;

ALTER TABLE LEASE_CATEGORY ADD CATEGORY_ACCOUNT_NAME VARCHAR(100) NULL;
ALTER TABLE LEASE_CATEGORY ADD CATEGORY_BANK VARCHAR(100) NULL;
ALTER TABLE LEASE_CATEGORY ADD CATEGORY_BSB VARCHAR(10) NULL;
ALTER TABLE LEASE_CATEGORY ADD CATEGORY_ACCOUNT_NUMBER VARCHAR(20) NULL;

ALTER TABLE LEASE_PREMISES CHANGE ADDRESS ADDRESS_LINE_ONE VARCHAR(200);
ALTER TABLE LEASE_PREMISES ADD ADDRESS_LINE_TWO VARCHAR(200) NULL;